### ISSUE TITLE
New guide: migrating keys to a new machine or cold storage

### ISSUE THREAD

**Issue by har00ga** [prysmaticlabs/documentation#129] opened 2020-05-27 15:41 UTC
Been requested multiple times over the past few mos but somehow keeps falling through the filed issue cracks: docs need a guide explaining how to safely migrate validator keys from one machine to another and how to properly store backups

**Comment by rauljordan** [comment] 2020-08-31 17:00
Duplicate of #224

**Closed by rauljordan** 2020-08-31 17:00 UTC
Labels: enhancement
