### ISSUE TITLE
Add a page for archival usage

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/documentation#221] opened 2020-08-27 00:34 UTC
As we head towards mainnet, we'll want a page  to advertise `--slots-per-archived-point` so that users that want to run "archival" node know how and when to use it. Example: 
https://lighthouse-book.sigmaprime.io/advanced_database.html

**Comment by rauljordan** [comment] 2021-02-05 22:47
Duplicate of #147

**Closed by rauljordan** 2021-02-05 22:47 UTC
Labels: priority:medium
